### ISSUE TITLE
Can I program this from within the Raspberry Pi?

### ISSUE THREAD

**Issue by vjoao** [matrix-io/matrix-creator-mcu#3]
I already cloned the `matrix-creator-openocd` to my raspberry and compiled it with
```
./bootstrap
./configure
make && sudo make install
```

 I also compiled this with the `cmake` command and I have the .hex file.

Do I need an external JTAG programmer or can I program it directly from the Pi (that would be awesome)?

Thanks for your time and for this amazing project =)

**Comment by kdpatino** [comment]
Yes, You could program the SAM3S with RPI3. We use OpenOCD to do it. So first check the .cfg file: https://github.com/matrix-io/matrix-creator-init/blob/master/cfg/sam3s_rpi_sysfs.cfg.

Creatr your own .cfg file and then run:
`sudo openocd -f NAME_FILE.cfg1`

Regards,

Kevin

**Comment by vjoao** [comment]
Great! Thanks =)
